# Generated by Django 3.1.1 on 2020-09-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jwtconnectauthtoken',
            old_name='token',
            new_name='access_token',
        ),
    ]
