# Generated by Django 3.1.1 on 2020-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_auth', '0002_auto_20200915_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='access_token',
            field=models.TextField(help_text='Token', unique=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='expire_at',
            field=models.DateTimeField(blank=True, help_text='Expire at', null=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='Issued At', null=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='jti',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Unique identifier for this token'),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='refresh_token',
            field=models.TextField(help_text='Refresh Token', unique=True),
        ),
    ]
