# Generated by Django 3.1.1 on 2020-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_auth', '0003_auto_20200915_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jwtconnectauthtoken',
            old_name='expire_at',
            new_name='access_expire_at',
        ),
        migrations.AddField(
            model_name='jwtconnectauthtoken',
            name='refresh_expire_at',
            field=models.DateTimeField(blank=True, help_text='Refresh expire at', null=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='audience',
            field=models.CharField(blank=True, help_text='Audience, recipients that the JWT isintended for. Multiple service/resource name for whom have been released', max_length=256, null=True, verbose_name='aud'),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='jti',
            field=models.CharField(blank=True, help_text='Unique identifier for the access token', max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='sid',
            field=models.CharField(blank=True, help_text='Django Session id', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jwtconnectauthtoken',
            name='sub',
            field=models.CharField(blank=True, help_text='Django opaque user identifier', max_length=256, null=True),
        ),
    ]
